server:
  # 服务端口
  port: 8080

gins:
  # 数据库
  datasource:
    enable: false
    path: "gins-mysql"
    port: "3306"
    config: ""
    db-name: "gins"
    username: "root"
    password: "123456"
    max-idle-conns: 10
    max-open-conns: 100
    log-mode: ""
    log-zap: false
    # redis
  redis:
    enable: false
    db: 0
    host: gins-redis
    port: 6379
    password: ""
  zap:
    level: info
    format: console
    prefix: github.com/twelvet-s/gins
    director: logs
    show-line: true
    encode-level: LowercaseColorLevelEncoder
    stacktrace-key: stacktrace
    log-in-console: true
