FROM golang:alpine as builder

WORKDIR /home/gins
COPY ../../ .

RUN go env -w GO111MODULE=on \
    && go env -w GOPROXY=https://goproxy.cn,direct \
    && go env -w CGO_ENABLED=0 \
    && go env \
    && go mod tidy \
    && go build -v

FROM alpine:latest

LABEL MAINTAINER="2471835953@qq.com"

WORKDIR /home/gins

COPY --from=0 /home/gins ./
COPY --from=0 /home/gins/resources ./resources/
COPY --from=0 /home/gins/application.release.yaml ./

EXPOSE 8888
ENTRYPOINT ./gins
