info:
  contact: {}
  description: Gins Swagger
  title: Gins API
  version: 1.0.0
paths:
  /:
    get:
      description: Welcome to gins pu
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Welcome to gins
      tags:
      - Index
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: x-token
    type: apiKey
swagger: "2.0"
