name: test

on:
  workflow_dispatch:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: init
        run: cd docker && chmod 751 ./deploy.sh && ./deploy.sh base

      - name: Build Gins
        run: go build -v && ls

      - name: Start Server
        run: cd docker && ./deploy.sh server

      - name: Check Server
        run: |
          cd docker
          sleep 10
          echo "Start checking the service, here are the service logs"
          docker logs --tail 500 gins
